
* LaTeX-KOMA-template

** Purpose of this project

This is a generic template for [[http://en.wikipedia.org/wiki/LaTeX][LaTeX]] documents using [[http://www.komascript.de/][KOMA Script]] classes
which are pretty common at least in German spoken countries.

The template does *not* want to contain each and every trick but should
provide a *clean*, *consistent* and *well documented* starting point for any
document exceeding a few pages. So if you plan to write a longer report,
a diploma thesis, a PhD thesis, or similar, this template should give you
a good basis.

The focus is that you - the author - is able to concentrate on the *content*
of your work rather than start fiddling around with the look of the document.
Several typographic optimizations are included in order to get a final document
that is optimized to deliver your content.

** What makes this template special?

The speciality of this template is, that every setting in the preamble is
*well documented* (in LaTeX). You can generate this documentation by your own
by not removing the template documentation include command in the main LaTeX
file and using [[http://www.gnu.org/software/make/][GNU make]] with the rule "templatedocu" followed by the rule "pdf":

#+begin_src sh
make templatedocu pdf
#+end_src

This command should result in a pdf file containing the documentation of this
template. Please refer to this PDF file for further information about
the template.

** How to start?

1. Put your desired PDF file name in the second line of file
   "Makefile"
   - replace "Projectname" with your filename
   - do not use any file extension like ".tex" or ".pdf"
2. generate the template documentation using [[http://www.gnu.org/software/make/][GNU make]]:
   - "make templatedocu pdf"
3. Read the generated PDF documentation of the template
4. Get rid of the template documentation
   - place a LaTeX comment character "%" in front of "\input{template_documentation}"
5. Modify files in the folder "preamble" if necessary
   - the PDF document documentation should give you an idea what to do
6. Modify "main.tex":
   - \myauthor
   - \mytitle
   - \mysubject
   - \mykeywords
   - your desired general document structure
7. replace or fill your content in "introduction.tex"
   - you can rename "introduction.tex" but then you have to modify
     its include command in "main.tex" too
8. create further tex-files (similar to "introduction.tex")for each
   chapter of your document
   - include them according to the example of "introduction" in "main.tex"
9. generate your document
   - with GNU make: "make pdf"
   - with plain command line: "pdflatex main.tex"
   - with a LaTeX editor:
     - select "main.tex" as the "main project file" or
     - compile/run only "main.tex" (and not "introduction.tex" or similar)
